export * from './AddClassDrawer'
export * from './AddStudent.popup'
export * from './AskBook.popup'
export * from './DeleteClass.popup'
export * from  './EditCLassname.popup'
export * from './Genatten.popup'
export * from './Mark.popup'
export * from './RemoveSt.popup'