export * from './Attendence/Attendence.controller'
export * from './Auth/auth.controller'
export * from "./Class/class.controller"
export * from "./Code/code.controller"
export * from "./Library/Library.Controller"
export * from "./Profile/profile.controller"
export * from "./Student/student.controller"
export * from "./StudentView/StudentView.controller"
export * from "./Teacher/Teacher.controller"